language: java
services:
  - docker

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

before_install:
  # Download compiled usql for ubuntu 16.04
  #- curl -O https://raw.githubusercontent.com/osalvador/disaster-box/master/usql
  #- chmod 777 usql
  #- sudo mv usql /usr/local/bin
  #- usql --version
  # Extract project.version from pom.xml
  - export REPLICADB_RELEASE_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
  - echo ${REPLICADB_RELEASE_VERSION}

install:
  - mvn clean install -Dmaven.javadoc.skip=true -B -V -P release
  - cp ./target/ReplicaDB-*.jar .
  - mkdir lib
  - cp ./target/lib/* ./lib  
  - tar -zcvf ReplicaDB-"${REPLICADB_RELEASE_VERSION}".tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE
  - zip -r -X ReplicaDB-"${REPLICADB_RELEASE_VERSION}".zip ReplicaDB-*.jar README.md lib conf bin LICENSE
  - ls -lahtr

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg REPLICADB_RELEASE_VERSION=${REPLICADB_RELEASE_VERSION} -t osalvador/replicadb:${REPLICADB_RELEASE_VERSION} .  
  - docker push osalvador/replicadb:${REPLICADB_RELEASE_VERSION}
  - docker build --build-arg REPLICADB_RELEASE_VERSION=${REPLICADB_RELEASE_VERSION} -t osalvador/replicadb .
  - docker push osalvador/replicadb

deploy:
  provider: releases
  api_key:
    secure: uTsJSmremnkRffvTxwaktVWQ6TShFN9kevhZM147jKF87/2HhUhxPO0qoGDRnALf/I3cUGVTDFA8TtpkSXC3sHChf4x/8t/wXxShSAUJbP1HdrC803s+BzA5lBwq8obiWWFTMwoceDJBYlC5ofisJwjIN0wR2h0pa5gOhU35sqo9dOdmEBE8QPIPYCPxKf3UFJZVNX7ewy57Ag3JYTTlYsV6qYhkBw0Z0Pb0SiaKH3pySYLl4r8KsA35mqlMW3U2vVhWSovGiP6amF9GBePUPRcVpAbdqq5tl7PIRqmLD6uPe93MDZ0jl5gtupNyAPWGHaeNj2ydXO5qpgkgk8mFJzafjAv0IbhVJMg95Dtch/abK8xWKxlFbcX1D8b7j507Bc1i9IA8YAEr3nj2bRq86AgS7yLQu3of5/o36ZPacOwRqVNbkoiswvHj/x4OuQ5C3ywUe/qrRmkDkEuw06G2tYl5XRNg8/TRkLMxcyUTfTJ1Yq2S4sp8EG5h5GEyF7yw5OkuD4eOaW4uvyB2wwfPULmGHwOfNSfzrwqW2qi/zKzt2tARn7r6uWn07OvlDbdbGKAa+pOInlwLmHLNXKR0c7Po629fLVntj7MktNXzB5pRGneojpQtS+pSiGhnmBEeQtWqPpolzVx9ojuwUddPwiVMuPEow8DqrE1x1sPv5Og=
  file: 
    - ReplicaDB-${REPLICADB_RELEASE_VERSION}.tar.gz
    - ReplicaDB-${REPLICADB_RELEASE_VERSION}.zip
  skip_cleanup: 'true'
  draft: true
  name: "release v${REPLICADB_RELEASE_VERSION}"
  on:
    tags: true
    branch: master
    repo: osalvador/ReplicaDB